Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [6]:
def turn_n_array(n):
    n_array = np.arange(0, n)
    n_array = n_array[::-1]
    print(n_array)

In [7]:
turn_n_array(20)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
def diagonal_matrix(n):
    n_array = np.arange(0, n)
    n_array = n_array[::-1]
    dia_matrix = np.diag(n_array)
    print(dia_matrix)

In [10]:
diagonal_matrix(15)

[[14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [9]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [10]:
from numpy import linalg

In [11]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [12]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [13]:
4*0.46666667+2*3.84444444+-5.55555556

4.0

In [14]:
0.46666667+3*3.84444444

11.999999990000001

In [15]:
5*3.84444444 + 4*-5.55555556

-3.0000000399999998

Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [12]:
# Матрица в виде numpy array
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [13]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [18]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return (np.dot( a, b ) / ( aLength * bLength ))

In [21]:
count = 0
max_coefficient = 0

for user in users_stats:
    count +=1
    user_coefficient = cosine(user, next_user_stats)
#     print(count, user_coefficient)
    if  user_coefficient > max_coefficient:
        max_coefficient = user_coefficient
        user_id = count
        user_array = user

print (f"Новый пользователь максимально близок по покупкам с пользователем с ID: {user_id}, коэффициент совпадения: {max_coefficient}, массив покупок: {user_array}")
        

Новый пользователь максимально близок по покупкам с пользователем с ID: 8, коэффициент совпадения: 0.9486832980505138, массив покупок: [0 1 1 0 0 0]
